import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import SearchBar from "../components/SearchBar";
import { WeatherApi } from "./api/WeatherApi";
export default function Home({ api }: { api: any }) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Weather-Forcast</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/logo_jt.svg" />
            </Head>
            <div>
                <SearchBar />
                <WeatherApi />
            </div>
        </div>
    );
}
